require("colorscheme")
require("keybinds")
require("lsp")
require("options")
require("plugins-blink-cmp")
require("plugins-gitsigns")
require("plugins-lualine")
require("plugins-nvim-tree")
require("plugins-nvim-treesitter")
require("plugins-telescope")
require("plugins-which-key")

