theme = "nightfox"

[editor]
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.whitespace]
render = "all"

[keys.normal]
X = "extend_line_above"
